### ISSUE TITLE
真机上运行报错

### ISSUE THREAD

**Issue by boyssimple** [qq3200341/FLWebRTCDemo#2]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'

#import "ShowVideosVC.h"
- (void)webRTCHelper:(WebRTCHelper *)webRTChelper addRemoteStream:(RTCMediaStream *)stream userId:(NSString *)userId
{
    RTCVideoTrack *track = [stream.videoTracks lastObject];
    [_videoTrackArray addObject:track];////track为nil
    [_userIdArray addObject:userId];
    [_myCollectionView reloadData];
}

**Comment by qq3200341** [comment]
这个错我知道，跟真机没关系，是我自己以前写的有问题，这个demo主要的意义是跑通流程。
